source 'https://rubygems.org'

gem('string-utility', '~> 3.0')
gem('mediawiki-butt', '~> 3.0')
gem('fishbans', '~> 2.0')
gem('weatheruby', '~> 1.0')
gem('cinch', '~> 2.3')
gem('literate_randomizer', '~> 0.4')
gem('twitter', '~> 6.1')
gem('require_all', '~> 2.0')
gem('simple_geolocator', '~> 2.0')
gem('octokit', '~> 4.7')
gem('array_utility', '~> 1.1')
gem('pastee', '~> 2.0')
gem('isgd', '~> 1.0')
gem('cleverbot_io', '~> 2.0')
gem('dotenv', '~> 2.7')
gem('urbandict', '~> 1.0')
gem('sequel', '~> 4.48')
gem('pg', '~> 0.21')
gem('curb', '~> 0.9')
gem('mojang', '>= 1.0.1')
gem('timerizer', '~> 0.2')
gem('oxford_dictionary', '~> 1.0')
gem('addressable', '~> 2.5')

ruby '2.6.3'
