source 'https://rubygems.org'

gem('string-utility', '~> 3.0')
gem('mediawiki-butt', '~> 3.0')
gem('fishbans', '~> 2.0')
gem('openweathermap', '~> 0.1')
gem('cinch', '~> 2.3')
gem('literate_randomizer', '~> 0.4')
gem('twitter', '~> 6.2')
gem('require_all', '~> 2.0')
gem('simple_geolocator', '~> 2.0')
gem('octokit', '~> 4.14')
gem('array_utility', '~> 1.1')
gem('pastee', '~> 2.0')
gem('isgd', '~> 1.0')
gem('dotenv', '~> 2.7')
gem('urbandict', '~> 1.0')
gem('sequel', '~> 5.22')
gem('pg', '~> 1.1')
gem('curb', '~> 0.9')
gem('mojang', '~> 1.0')
gem('timerizer', '~> 0.3')
gem('mw_dictionary_api', '~> 0.1')
gem('addressable', '~> 2.6')

ruby '2.6.5'
