source 'https://rubygems.org'

gem('string-utility', '~> 2.7', '<= 2.7.2')
gem('mediawiki-butt', '~> 1.3')
gem('fishbans', '~> 1.1')
gem('weatheruby', '~> 0.6')
gem('cinch', '~> 2.3')
gem('literate_randomizer', '~> 0.4')
gem('twitter', '~> 6.1')
gem('require_all', '~> 1.3')
gem('simple_geolocator', '~> 2.0')
gem('octokit', '~> 4.3')
gem('array_utility', '~> 1.1')
gem('pastee', '~> 2.0')
gem('isgd', '~> 1.0')
gem('cleverbot_io', '~> 1.2')
gem('dotenv', '~> 2.1')
gem('urbandict', '~> 1.0')
gem('sequel', '~> 4.34')
gem('pg', '~> 0.18')
gem('curb', '~> 0.9')
gem('mojang', '>= 1.0.1')
gem('timerizer', '~> 0.1')
gem('oxford_dictionary', '~> 0.1')

ruby '2.3.0'
